### ISSUE TITLE
Allow directory local specification of packages

### ISSUE THREAD

**Issue by hugoduncan** [borkdude/cpm#20]
For use with project specific tooling, allow specification of packages in a project local configuration directory.

This may require https://github.com/borkdude/glam/issues/15 to ensure the package definition correspond with the installed packages.

**Comment by borkdude** [comment]
@hugoduncan For the globally installed packages glam writes to `~/.glam/installed.edn` when you run `glam install ... -g`. E.g. on my system I have:

``` 
{org.babashka/babashka "0.2.2", tzzh/pod-tzzh-aws "0.0.2"}
``` 

This is the source for creating `~/.glam/path` which is in turn used to add packages globally to the path.

Additionally we could have a similar EDN file that's part of the user config (both globally and locally), that we don't programmatically touch as to preserve comments, whitespace, etc and merge these two for producing `~/.glam/path`.

**Comment by hugoduncan** [comment]
The use case is to implement a self contained project build.  The idea is that you can check out a project and run all the build targets without explicitly installing all the required tools.  The build system would use glam to install the tools, at their expected versions. For this, the project would need to provide package edn files for all the tools that weren't in glam's core configuration.  Ideally the config files would not need to become part of the user's config, so the user's config is not polluted once they have finished working on the project.

**Comment by borkdude** [comment]
Yes. Note that glam currenly supports `repositories.edn` in the global config. We could also support this in directly local config, so the packages are pulled in automatically and can be updated out of band, but we can also support non-git repos by just having package glam.edn files without git, in a dir.

**Comment by borkdude** [comment]
@hugoduncan It seems NPM just re-formats `package.json` when you `npm install` something. We might just do the same and have one .edn file which is editable by users but to which glam also will write updates and then pprint the edn file. 
This won't allow comments in the EDN file, maybe that's a reasonable trade-off to have one source of the truth?

**Comment by hugoduncan** [comment]
Having a single file at the per-directory level is certainly very workable.

**Comment by borkdude** [comment]
@hugoduncan I experimented with an approach where glam can update files that users also edit themselves, while preserving comments, etc:

https://github.com/borkdude/rewrite-edn

If feels like a bit of a rabbit hole.

Maybe it's better if glam doesn't support `install foo/bar` but users always edit an edn file, like you do with deps.edn (which also doesn't have commands to update its config files)?

**Comment by borkdude** [comment]
@hugoduncan I now put everything into one global + local config file. See the new README.
