### ISSUE TITLE
Make glam-bin installable via glam

### ISSUE THREAD

**Issue by hugoduncan** [borkdude/cpm#25]
Facilitate installation on `glam-bin` when Clojure cli is available by making glam-bin installable by running glam via `clj -Sdeps`.  This would also make it easy to install a specific version of glam.

**Comment by borkdude** [comment]
@hugoduncan I added glam/glam now to https://github.com/glam-pm/packages. It does not run `glam-bin setup` yet. We should probably add support for running scripts like that.
